<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms><ApplicationManifest>app.manifest</ApplicationManifest><AssemblyName>RoutineRest</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../RoutineRest.Core/RoutineRest.Core.csproj" /></ItemGroup></Project>